title: Homepage
author: Lilia Alanís López
email: lilia.alanislpz@uanl.edu.mx
description: "¡Hola!... espacio de colaboración... muchas gracias por sus consejos y trabajo"
# social links
twitter_username: LiliaAlanis2
github_username:  LiliaAlanis

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
